sonar.organization=agustin-perez-data
sonar.projectKey=agustin-perez-data_APIS2-G5-RECLAMOS-BACKEND

sonar.sources=app
sonar.tests=tests
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml